{
	"_Type": "Action.Type.Logger.Upload",
	"OnSuccess": "/SalesOrdersOnline/Actions/Logger/LogUploadSuccessMessage.action",
	"OnFailure": "/SalesOrdersOnline/Actions/Logger/LogUploadFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": " "	
}