{
	"ActionResult": {
		"_Name": "result"
	},
	"OnFailure": "/SalesOrdersOnline/Actions/SalesOrder/CreateUpdateDelete/SOLifeCycleStatusChangeFailure.action",
	"OnSuccess": "/SalesOrdersOnline/Actions/SalesOrder/CreateUpdateDelete/SOLifeCycleStatusChangeSuccess.action",
	"Properties": {
		"LifeCycleStatus": "R",
		"LifeCycleStatusName": "Rejected"
	},
	"Target": {
		"EntitySet": "SalesOrderHeaders",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SalesOrdersOnline/Services/SampleSrv.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}